node {
 
 stage('Git CheckOut') {
    git branch: 'main', url: 'https://github.com/janardhan455/CaseStudy_301_Srirama.git'
 }
 
 def project_path="JenkinsPipeLine/petclinic-code"
 
 dir(project_path) {
 
 stage('Maven Clean') {
    sh 'mvn clean'
 }
 
  stage('Maven Compile') {
    sh 'mvn compile'
 }
 
 stage('Maven Testing') {
    sh 'mvn test'
 }
 
 stage('Maven Package') {
    sh 'mvn package'
 }
 
 stage('Archive Artifacts') {
    archive 'target/*.war'
 }
 }
 }